import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/header/Navbar";
import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NextTopLoader color="black" height={7}/>
      <Navbar/>
      {children}
      </body>
    </html>
  );
}
